POST http://localhost:8081/events 
Content-Type: application/json
Authorization: ""

{
    "name": "Party",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}